export const config = {
  years: ["2022"],
  propertyPrices: {
    fetch: false,
  },
  titles: {
    mimhTitle: "MPF/MI",
    indexTitle: "Göteborgs Boendeprisindex",
    indexShortTitle: "GBPI",
    indexSubTitle: "En indikation på bostadstillgänglighet",
    ownershipRateTitle: "Ägarandel %",
    medianQueueTimeTitle: "Mediankötid",
    medianRentTitle: "Medianhyra/kvm (2hand)",
  },
  scales: {
    gothenburgMedianIncomeToMedianHousePrice: 0.3,
    ownershipRate: 0.1,
    medianQueueTime: 0.3,
    medianRent: 0.3,
  },

  areaMapping: {
    Angered: [
      "604 Angereds Centrum",
      "605 Agnesberg",
      "611 Bergum",
      "613 Eriksbo",
      "610 Gunnilse",
      "603 Gårdstensberget",
      "606 Hammarkullen",
      "612 Hjällbo",
      "609 Linnarhult",
      "601 Lövgärdet",
      "602 Rannebergen",
    ],
    "Askim-Frölunda-Högsbo": [
      "523 Askim",
      "525 Billdal",
      "510 Flatås",
      "517 Frölunda Torg",
      "524 Hovås",
      "511 Högsbohöjd",
      "512 Högsbotorp",
      "515 Järnbrott",
      "509 Kaverös",
      "514 Ruddalen",
      "513 Tofta",
      "516 Högsbo",
    ],
    Centrum: [
      "113 Guldheden",
      "116 Inom Vallgraven",
      "111 Johanneberg",
      "110 Krokslätt",
      "112 Landala",
      "114 Lorensberg",
      "117 Stampen",
      "115 Vasastaden",
      "118 Heden",
    ],
    Lundby: [
      "416 Eriksberg",
      "402 Kvillebäcken",
      "414 Kyrkbyn",
      "404 Kärrdalen",
      "417 Lindholmen",
      "415 Rambergsstaden",
      "403 Slättadamm",
      "407 Kärra",
    ],
    "Majorna-Linné": [
      "108 Annedal",
      "107 Haga",
      "109 Olivedal",
      "103 Majorna",
      "105 Masthugget",
      "101 Kungsladugård",
      "102 Sanna",
      "104 Stigberget",
      "106 Änggården",
    ],
    "Norra Hisingen": [
      "412 Backa",
      "410 Brunnsbo",
      "408 Rödbo",
      "409 Skogome",
      "413 Skälltorp",
      "406 Säve",
      "405 Tuve",
    ],
    "Västra Göteborg": [
      "506 Bratthammar",
      "501 Fiskebäck",
      "520 Grevegården",
      "504 Grimmered",
      "507 Guldringen",
      "503 Hagen",
      "522 Kannebäck",
      "502 Långedrag",
      "521 Näset",
      "508 Skattegården",
      "505 Södra Skärgården",
      "518 Ängås",
      "519 Önnered",
    ],
    "Västa Hisningen": [
      "707 Arendal",
      "706 Björlanda",
      "704 Hjuvik",
      "709 Jättesten",
      "702 Länsmansgården",
      "705 Nolered",
      "701 Norra Biskopsgården",
      "703 Svartedalen",
      "708 Södra Biskopsgården",
    ],
    "Örgryte-Härlanda": [
      "203 Bagaregården",
      "212 Björkekärr",
      "209 Härlanda",
      "204 Kallebäck",
      "210 Kålltorp",
      "207 Kärralund",
      "208 Lunden",
      "201 Olskroken",
      "202 Redbergslid",
      "205 Skår",
      "211 Torpa",
      "206 Överås",
      "207 Kärralund",
    ],
    "Östra Göteborg": [
      "301 Gamlestaden",
      "304 Norra Kortedala",
      "303 Södra Kortedala",
      "302 Utby",
      "305 Västra Bergsjön",
      "306 Östra Bergsjön",
    ],
  },
  classification: {
    1: {
      status: "Enkelt",
      color: "#66A182",
    },
    2: {
      status: "Möjligt",
      color: "#4B8F72",
    },
    3: {
      status: "Utmanande",
      color: "#3B7D63",
    },
    4: {
      status: "Svårt",
      color: "#2C6B54",
    },
    5: {
      status: "Mycket svårt",
      color: "#1C4D3B",
    },
  },
};
